### ISSUE TITLE
am unable to set keybinds inside of clone hero.

### ISSUE THREAD

**Issue by thatguycore** [artman41/FenderStratocastorSniffer#1]
I am unable to set key binds inside of Clone Hero. The most I am ever able to set is maybe green, after that I am unable to set any additional key binds even though the sniffer software detects that I am pressing guitar inputs.

**Comment by artman41** [comment]
I believe the issue is that the accelerometer is being detected at the same time and messing with the input, if you hold the guitar down so that input is not affecting your data, does the guitar work?

**Comment by thatguycore** [comment]
Even if I hold the guitar perfectly still on a flat surface things tend to mess up. A lot of times with the sniffer active I have noticed that I am unable to properly do any input in clone hero, including using my keyboard. If I disable the sniffer then I am able to use the keyboard to set inputs again. I'll set up the proper inputs in game and load up the sniffer again but then inputs "stick". Which I believe is something you mentioned in the readme anyways. But yeah, if I press green then green is constantly held down and never releases. Same with other colors.

**Comment by artman41** [comment]
thanks for the info, gonna tag #3 since this seems like a related issue 😄

**Comment by thatguycore** [comment]
this was closed but I will comment here instead of creating a new topic. When using the "start" key on the controller it exhibits some of the same behavior as other keys when they "stick" I can use the start button to access the menu in a song but the start button will no longer be usable unless i tab in and out of Clone Hero. I also lose functionality of the esc key on my keyboard which acts the same as the start button on my controller.

**Comment by artman41** [comment]
I noticed that too, Fixed and a new version uploaded :)
