### ISSUE TITLE
Bottom Fret

### ISSUE THREAD

**Issue by GauravMenon** [artman41/FenderStratocastorSniffer#12]
So the 4.0 release doesn't really work. And the 3.0 build shows that the bottom fret buttons work. But that every time a bottom fret is pressed, the strum is released. Any reason why?

**Comment by artman41** [comment]
no idea, new sniffer is out at https://github.com/artman41/guitarsniffer, check that instead please

**Comment by GauravMenon** [comment]
This new one is great! Thanks! It also fixed the bottom fret problem
