### ISSUE TITLE
Please help and hopefully in a reasonable amount of time. I saw it took a week to even get a response. (RB4 Strat Xbox One to PC)

### ISSUE THREAD

**Issue by BoggleJ** [artman41/FenderStratocastorSniffer#13]
Trying to setup stratocaster with wireless adapter. I had a problem originally with just connecting the thing but after searching for correct drivers finally got it working and connected with my guitar. However it does not work with clone hero and does not even detect it as a controller. when i go to joy.cpl it does not even display any "controller" what so ever. Therefore in clone hero it doesn't detect anything. I tried getting support from the clone hero discord but they were baffled as to why it did not work and told me to go here.

Ive tried restarting updating windows administrator on all programs etc. Everything basic most likely you could think of and the clone hero discord could think of please help i really want to enjoy this game while i still have days off from work.

![clone](https://user-images.githubusercontent.com/54969347/64397104-e0be4500-d014-11e9-91f7-d5e3a2163cf1.png)
![sniffer](https://user-images.githubusercontent.com/54969347/64397105-e156db80-d014-11e9-8133-825bdaae1d1e.png)

![joy cpl](https://user-images.githubusercontent.com/54969347/64397138-fcc1e680-d014-11e9-8b18-a881ec79dacf.png)

**Comment by artman41** [comment]
Hi @BoggleJ, not to be rude, but did you read the front page of the project?
![image](https://user-images.githubusercontent.com/5568965/64451269-bc796b80-d0db-11e9-9e8e-12354a3337bd.png)

There was a huge rewrite of the project to change the language it was written in and to improve upon it.

Please try the project found [here](https://github.com/artman41/guitarsniffer) instead and create an issue if that project doesn't work for you.

Thanks :)
