### ISSUE TITLE
Notes not registered when playing songs.

### ISSUE THREAD

**Issue by thatguycore** [artman41/FenderStratocastorSniffer#5]
So it seems that all the sticky issues are fixed. However now it seems there is an issue where Clone Hero doesn't register all the notes being played or maybe the response time on the controller is slow? I tried one song on medium with the xbox controller and missed a lot of notes. Played the same song on a ps4 jaguar controller and was able to play notes to my normal ability.

**Comment by artman41** [comment]
Think this is done? might want to give it another test with the latest build
